print("Welcome to the DevOps Learning Journey with Jenkins!")
print("This script, main.py, is your starting point.")
print("Get ready to explore the world of DevOps practices and automation.")
print("Follow along as we dive into Jenkins and learn how it can streamline your workflows.")
print("Let's embark on this exciting learning adventure together!")
